#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_mod = env_modules.Clone()

# Thirdparty source files
thirdparty_obj = []
thirdparty_dir = "thirdparty/sqlite/"
thirdparty_sources = ["sqlite3.c"]
thirdparty_sources = [thirdparty_dir + file for file in thirdparty_sources]

env_thirdparty = env_mod.Clone()
env_thirdparty.disable_warnings()
env_thirdparty.Append(CPPEXTPATH=[thirdparty_dir])

if env.msvc:
    env_thirdparty.Append(CCFLAGS=["/fp:precise"])
env_thirdparty.add_source_files(thirdparty_obj, thirdparty_sources)
env.modules_sources += thirdparty_obj

# Enable SQLite FTS5 Extension.
# env_mod.Append(CPPDEFINES=["SQLITE_ENABLE_FTS5"])

# Godot source files

module_obj = []

env_mod.add_source_files(module_obj, "*.cpp")
env_mod.add_source_files(module_obj, "vfs/*.cpp")
env.modules_sources += module_obj

# Needed to force rebuilding the module files when the thirdparty library is updated.
env.Depends(module_obj, thirdparty_obj)
